### ISSUE TITLE
Create Admin

### ISSUE THREAD

**Issue by V-FOR-VEND3TTA** [V-FOR-VEND3TTA/django-blog#1]
Django provides a built-in admin panel for managing your data. To add your Post model to the admin panel, open blog/admin.py and register the model:

`from django.contrib import admin
from .models import Post

admin.site.register(Post)`

**Comment by VidyaYadavv1519** [comment]
Can you assign me this ??

**Comment by V-FOR-VEND3TTA** [comment]
> Can you assign me this ??

Sure. Just make sure you commit to a different branch before we merge
