### ISSUE TITLE
Create views

### ISSUE THREAD

**Issue by V-FOR-VEND3TTA** [V-FOR-VEND3TTA/django-blog#2]
Create views and templates for your blog. Create a blog/views.py file and define views to handle displaying the list of posts and individual post pages. Create corresponding templates in the blog/templates directory.

`from django.shortcuts import render
from .models import Post

def post_list(request):
    posts = Post.objects.all()
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = Post.objects.get(pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})
`

**Comment by VidyaYadavv1519** [comment]
Can you assign me this ??

**Comment by V-FOR-VEND3TTA** [comment]
> Can you assign me this ??

Sure. I will

**Comment by VidyaYadavv1519** [comment]
So, Can i fork this project now ??

**Comment by V-FOR-VEND3TTA** [comment]
> So, Can i fork this project now ??

Absolutely

**Comment by V-FOR-VEND3TTA** [comment]
Sure. Go ahead. This is an open source project, your help in advancing it
is appreciated.
