### ISSUE TITLE
Create URL Patterns

### ISSUE THREAD

**Issue by V-FOR-VEND3TTA** [V-FOR-VEND3TTA/django-blog#3]
In the myblog directory, open urls.py and define URL patterns for your blog app:

`from django.urls import path
from blog import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
]
`

**Comment by VidyaYadavv1519** [comment]
Can you assign me this ??

**Comment by V-FOR-VEND3TTA** [comment]
> Can you assign me this ??

Done. And please remember to create a new branch before we merge
