### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by V-FOR-VEND3TTA** [V-FOR-VEND3TTA/django-blog#5]
Open your project's settings file (myblog/settings.py) and make the following updates:

- [x] Add 'django.contrib.auth' and 'django.contrib.contenttypes' to the INSTALLED_APPS list if they're not already there.

`INSTALLED_APPS = [
    # ...
    'django.contrib.auth',
    'django.contrib.contenttypes',
    # ...
]
`

- [x] Configure the authentication backends to use the built-in ModelBackend. Add or update the AUTHENTICATION_BACKENDS setting:
`AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
`

- [x] Set the LOGIN_REDIRECT_URL to specify where users will be redirected after a successful login. You can create a custom view for this later if needed. For now, you can set it to the admin site:
`LOGIN_REDIRECT_URL = '/admin/'
`
- [x] Create user authentication views
Django comes with built-in views and templates for user authentication. You can use these views as they are or customize them according to your needs. To include the authentication views in your project, update your app's urls.py:
`from django.contrib.auth import views as auth_views

urlpatterns = [
    # ...
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # ...
]
`

- [x] Create user registration
If you want to allow users to register for your blog, you can create a registration view and template. Here's a simplified example of how to do it:
Create a registration view in your blog/views.py:
`from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.shortcuts import render, redirect

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('post_list')  # Redirect to the desired page after registration.
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form': form})
`
Create a registration template (registration/register.html) where users can fill out the registration form.

Update your app's urls.py to include the registration view:

`from django.contrib.auth import views as auth_views
from blog import views as blog_views

urlpatterns = [
    # ...
    path('register/', blog_views.register, name='register'),
    # ...
]
`
- [x] Create login and logout links in templates
In your blog templates (e.g., base.html), add links to login and logout views

`{% if user.is_authenticated %}
  <a href="{% url 'logout' %}">Logout</a>
{% else %}
  <a href="{% url 'login' %}">Login</a>
{% endif %}
`

**Comment by VidyaYadavv1519** [comment]
Hiii
Can you assign me this issue ??

**Comment by V-FOR-VEND3TTA** [comment]
> Hiii Can you assign me this issue ??

Sure. You're in it now
